### ISSUE TITLE
"Reset Filter" returns to default grid view

### ISSUE THREAD

**Issue by ecullar** [jayelkaake/enhancedgrid#30]
When you hit "reset filter" in the grid view, it returns a default version of the grid view. Hitting refresh or getting to that page any other way will show the customized view we set. 

This is the customized view (how it's supposed to work)
![image](https://cloud.githubusercontent.com/assets/16709394/12336684/c6e2beb8-bad3-11e5-87e5-010f2453a67b.png)

When you hit the reset filter button, it comes back with this:
![image](https://cloud.githubusercontent.com/assets/16709394/12336672/b2b4bfcc-bad3-11e5-83ad-742193356e00.png)

We have version 1.3.4.3 .

**Comment by jayelkaake** [comment]
I'm working on resolving this - I'll have a fix soon.

**Comment by ecullar** [comment]
I wasn't expecting a follow so shortly. Thank you for letting me know!


On 2016-01-14 6:44 pm, Jay El-Kaake wrote:
> I'm working on resolving this - I'll have a fix soon.
> 
> --
> Reply to this email directly or view it on GitHub [1].
> 
> 	* --------------------------------------------------------------
> 
> Links:
> ------
> [1] 
> https://github.com/jayelkaake/enhancedgrid/issues/30#issuecomment-171819105

-- 
-----------------------------------------------------------------

**Comment by jayelkaake** [comment]
I'm actually unable to recreate the issue... ![](http://g.recordit.co/vVqueWMsxC.gif)

There may be a module conflict happening somewhere since some other modules sometimes rewrite the grid components. Try using a module conflict checker extension to see if there are any module conflicts. 

If you get the chance to check for that please post back your results.
