### ISSUE TITLE
Showing back and advance buttton

### ISSUE THREAD

**Issue by pranavcp** [jayelkaake/enhancedgrid#55]
It is showing following like two buttons in admin.
http://prntscr.com/e5ieau

Any idea how to remove these?

**Comment by jayelkaake** [comment]
Weird...remove line 32 from this file and you'll be good to go https://github.com/jayelkaake/enhancedgrid/blob/master/app/design/adminhtml/default/default/template/tbt/enhancedgrid/catalog/product.phtml

**Comment by pranavcp** [comment]
Nop, still showing the same issue. I have tried, but still showing the same.

**Comment by jayelkaake** [comment]
Hmmm... What extensions do you have installed?

On Feb 8, 2017 10:36 PM, "pranavcp" <notifications@github.com> wrote:

Nop, still showing the same issue. I have tried, but still showing the same.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/jayelkaake/enhancedgrid/issues/55#issuecomment-278545115>,
or mute the thread

**Comment by pranavcp** [comment]
Also, sometimes it is showing yellow bar before Add Product button.

**Comment by pranavcp** [comment]
For product grid, this is only one.

**Comment by jayelkaake** [comment]
Yeah I understand but this is not happening  to anyone else with tens of
thousands of merchants and there is no code in enhanced grid that would do
this. You need to check other extensions that are modifying this.

**Comment by pranavcp** [comment]
Ok, let me check from side and debug your extension also. Will keep posted here if anything from extension.

**Comment by jayelkaake** [comment]
Sounds good - thanks!

**Comment by pranavcp** [comment]
That is coming from iframe, file
app/code/community/TBT/Enhancedgrid/Block/Widget/Loyalty.php
Code is, 
<iframe src="{$this->_getLoyaltyUrl()}" marginwidth="0" marginheight="0"
                	align="middle" frameborder="0"
                    scrolling="no" style="width: 500px; float: left; height: 22px;">
</iframe>

Shall I remove this?

**Comment by jayelkaake** [comment]
That's what I told you to remove in the fist place :p. Yes remove it.

On Feb 9, 2017 12:12 AM, "pranavcp" <notifications@github.com> wrote:

That is coming from iframe, file
app/code/community/TBT/Enhancedgrid/Block/Widget/Loyalty.php
Code is,
<iframe src="{$this->_getLoyaltyUrl()}" marginwidth="0" marginheight="0"
align="middle" frameborder="0" scrolling="no" style="width: 500px; float:
left; height: 22px;"> </iframe>

Shall I remove this?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/jayelkaake/enhancedgrid/issues/55#issuecomment-278556599>,
or mute the thread

**Comment by pranavcp** [comment]
Ha ha ha, you told me to remove that from phtml file, any ways  thanks for promt replies everytime and valuable time.
