### ISSUE TITLE
If I knew I was going to see your bullshit popups?

### ISSUE THREAD

**Issue by gfxguru** [jayelkaake/enhancedgrid#57]
I would have never installed. People don't use this extension. There are plenty out there that do the same without the crap.

**Comment by jayelkaake** [comment]
I wish I could remove it. I get no benefit. Since I built this while I was at my last company they won't let me remove it from the main code base :(

You can remove it yourself if you want. Just delete this line:
https://github.com/jayelkaake/enhancedgrid/blob/master/app/design/adminhtml/default/default/template/tbt/enhancedgrid/catalog/product.phtml#L32
